 {{ config(materialized='table') }}
 WITH LINE AS (SELECT A.*,B.L_ORDERKEY,B.L_DISCOUNT,B.L_SHIPDATE,B.L_SHIPMODE,C.P_NAME FROM SLEEKMART_OMS.L1_LANDING.PARTSUPP AS A
LEFT JOIN LINEITEM AS B ON A.PS_PARTKEY=B.L_PARTKEY
LEFT JOIN PART AS C ON B.L_PARTKEY=C.P_PARTKEY)
SELECT * FROM LINE