with EMP_SAL AS (SELECT A.EID,A.EFNAME,A.ELNAME,A.EAGE,A.ESEX,A.EDEPT,A.DEPT_DESCRIPTION,A.ELOCATION,B.ESAL
 FROM {{ref('EMP_LOCATION')}} AS A INNER JOIN COMP_STG.EMP_SALARY AS B
WHERE A.EID=B.EID)
SELECT A.*,B.COMPANY_NAME FROM EMP_SAL AS A LEFT JOIN {{ref('emp_company')}} AS  B WHERE A.EID=B.EID
--dbt build --model EMP_SAL