with EMP_LOC AS (SELECT A.EID,A.EFNAME,A.ELNAME,A.EAGE,A.ESEX,B.EDEPT,B.DEPT_DESCRIPTION,C.ELOCATION
FROM {{ref('EMP_DETAILS')}} AS A INNER JOIN {{ref('EMP_DEPT')}} AS B ON A.EID=B.EID
INNER JOIN COMP_STG.EMP_LOCATION AS C ON A.EID=C.EID)
SELECT * FROM EMP_LOC
--dbt build --model EMP_LOCATION